import React from "react";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

export const metadata = {
  title: "Terms of Service | Persuaide",
  description:
    "Persuaide Terms of Service - Read the terms governing your use of our platform.",
};

const termsOfServiceData = {
  intro: [
    `These Terms of Service ("Terms") govern your access to and use of the PERSUAIDE website (the "Website"), which is operated by Persuaide Software Solutions Pvt. Ltd. (doing business as "PERSUAIDE", "persuaide.ai", "we," "us," or "our").`,

    `These Terms apply to all visitors, users, and others who access our Services ("Users" “You” “Your”).`,
  ],

  sections: [
   {
  title: "1. Acceptance of Terms",

  paragraphs: [
    `By accessing or using the Website and/or the PERSUAIDE Platform (collectively, the "Services"), You acknowledge that You have read, understood, and agree to be bound by these Terms, the Privacy Policy, and any additional terms applicable to certain features of the Services, all of which are incorporated into these Terms by reference.`,

    `By accessing or using the Website, You agree to be bound by these Terms.`,

    `If You do not agree to these Terms, You are prohibited from using or accessing the Website.`,
  ],
},

{
  title: "2. About PERSUAIDE and This Website",

  paragraphs: [
    `PERSUAIDE is an artificial intelligence and behavioural science-powered platform that provides tools for brand campaign creation, creative asset generation, and marketing content optimization, accessible through a subscription model.`,

    `The Platform is designed as an assistive productivity tool to help marketing professionals, brand managers, agencies, and users streamline creative workflows, improve campaign efficiency, and enhance productivity in branding and marketing-related tasks.`,

    `PERSUAIDE leverages automated and technology-driven processes to support the generation, analysis, and organization of brand and marketing content; however, it does not provide and is not intended to provide professional marketing advisory, brand consulting, or advertising compliance services.`,

    `PERSUAIDE facilitates the processing of content uploaded or generated by Users and does not independently originate such content, except to the extent of automated outputs generated based on User inputs.`,

    `As these outputs are generated by automated systems, Users are solely responsible for independently reviewing, verifying, and validating all results prior to any professional use or reliance, including ensuring compliance with applicable advertising standards and intellectual property laws.`,

    `Any such processing is carried out in accordance with these Terms and applicable law.`,

    `This Website is intended to provide information about our products and Services, facilitate demo bookings, enable user inquiries through contact forms, and provide access to the Platform’s brand campaign creation Services ("Permitted Purpose").`,
  ],
},

{
  title: "3. Scope of these Terms",

  paragraphs: [
    `These Terms govern your access to and use of all websites, applications, content, and services owned or operated by Persuaide Software Solutions Pvt. Ltd.`,

    `This includes, but is not limited to, our public-facing informational website and our subscription-based AI and Behavioural Science-powered brand campaign platform (“PERSUAIDE Platform”).`,
  ],
},

{
  title: "4. User Obligations and Acceptable Use",

  subsections: [
    {
      title: "4.1. Eligibility",

      paragraphs: [
        `By using this Website, You represent and warrant that You are at least 18 (eighteen) years old and have the legal capacity to enter into these Terms.`,

        `If You are under 18 (eighteen), you may only use the Website with the consent and supervision of a parent or guardian.`,
      ],
    },

    {
      title: "4.2. Limited License",

      paragraphs: [
        `We grant you a limited, non-exclusive, non-transferable, and revocable license to access and use the Services (including the Website and the PERSUAIDE Platform) strictly for the Permitted Purpose and in accordance with these Terms.`,
      ],
    },

    {
      title: "4.3. Prohibited Activities",

      paragraphs: [
        `You agree not to:`,
      ],

      bullets: [
        "Use the Services (including the Website and the PERSUAIDE Platform) for any unlawful purpose or in violation of any applicable local, state, national, or international law;",

        "Scrape, reverse-engineer, decompile, or otherwise attempt to gain unauthorized access to any part of the Services (including the Website and the PERSUAIDE Platform), its underlying algorithms, prompts, or source code;",

        "Transmit any viruses, malware, worms, or other harmful or disruptive code;",

        "Interfere with or disrupt the security, integrity, or performance of the Services (including the Website and the PERSUAIDE Platform) or the data contained therein;",

        `Use the Services (including the Website and the PERSUAIDE Platform) for any commercial purpose exceeding the scope of Your subscription, including reselling, sub-licensing, or providing "service bureau" access to third parties; and`,

        "Share login credentials or allow unauthorized access.",

        "Upload, generate, transmit, or otherwise make available any content that is unlawful, fraudulent, misleading, or in violation of applicable law.",

        "Use the Services to generate, reproduce, or disseminate any content that infringes or misappropriates any third-party intellectual property rights, including trademarks, copyrights, designs, or trade secrets, or that constitutes passing off under applicable law;",

        "Use the Services to create brand assets, campaign materials, or marketing content that is misleading, deceptive, or in violation of the Advertising Standards Council of India (ASCI) Code, the Consumer Protection Act, 2019, or any other applicable advertising regulations;",

        "Upload, input, or otherwise make available on the Platform any proprietary brand assets, trademarks, creative materials, or confidential information belonging to third parties without obtaining all necessary rights, consents, and authorizations from such third parties;",
      ],

      extraParagraphs: [
        `The Company reserves the right to remove, disable access to, or restrict any content or activity that it reasonably believes to be in violation of applicable law or these Terms, including pursuant to lawful orders of competent authorities.`,
      ],
    },

    {
      title: "4.4. Misuse and Penalties",

      paragraphs: [
        `In case of misuse or violation of these Terms, PERSUAIDE reserves the right to:`,
      ],

      bullets: [
        "Suspend or terminate your access to the PERSUAIDE Platform.",

        "Impose penalties, including additional fees for unauthorized or excessive usage.",

        "Pursue legal remedies, if applicable.",
      ],
    },

    {
      title: "4.5. Compliance",

      paragraphs: [
        `Users must comply with all applicable laws, regulations, and internal company policies while using the platform.`,
      ],
    },

    {
      title: "4.6. Incident Reporting",

      paragraphs: [
        `Users must promptly notify PERSUAIDE at anand@persuaide.ai of any unauthorized use, suspected security breach, or compromise of account credentials.`,
      ],
    },

    {
      title: "4.7. Payment Terms",

      bullets: [
        "Users exceeding notified usage limits (e.g., number of documents, creatives, campaigns or users) will be charged extra as per applicable rates.",

        "Payments must be made within the specified timelines to avoid late payment charges or service suspension.",
      ],
    },
  ],
},


{
  title: "5. Intellectual Property Rights",

  paragraphs: [
    `All content, features, and functionality on this Website, including but not limited to text, graphics, logos, images, software, and the compilation thereof (collectively, the "Content"), are the exclusive property of PERSUAIDE or its licensors.`,

    `The '[PERSUAIDE]' name, logo, and all related names, logos, product and service names, designs, and slogans are trademarks of PERSUAIDE.`,

    `You must not use such marks without our prior written permission.`,

    `All Content is protected by Indian and international copyright, trademark, and other intellectual property laws.`,

    `Any use of the Website not expressly permitted by these Terms is a breach and may violate these laws.`,

    `The User retains all intellectual property rights in relation to the content that is uploaded onto the Platform and automatically grants Us a limited licence solely for the purpose of providing the Services.`,
  ],
},

{
  title: "6. Privacy and Data Protection",

  subsections: [
    {
      title: "6.1. Ownership of Data",

      paragraphs: [
        `All data input and output by the User ("Customer Data") remains the sole property of the User or their organization.`,

        `PERSUAIDE shall not use User data to train, fine-tune, or improve its underlying AI models without the User's prior written consent, except to the extent necessary to provide the Services.`,
      ],
    },

    {
      title: "6.2. Data Processing",

      paragraphs: [
        `To provide its comprehensive suite of brand campaign creation technology tools, PERSUAIDE utilizes a hybrid infrastructure consisting of proprietary in-house behavioural science knowledge and methods, and external third-party AI service providers.`,

        `By using the platform, you authorize the processing of data through these systems as necessary to deliver the requested automated outputs and platform functionalities.`,

        `Interaction data may be used to monitor platform performance and improve the efficiency of our services.`,

        `As these external AI providers operate as independent entities, you acknowledge that PERSUAIDE liability for the internal operations or policies of these third-party systems is limited to the extent permitted by law.`,

        `All processing within systems under PERSUAIDE direct control is performed strictly according to User instructions and the functional requirements of the Platform.`,

        `Upon termination of your subscription, Customer Data will not be retained, except as required for compliance with applicable law, enforcement of legal rights, or for limited archival and backup purposes in accordance with standard data retention practices.`,
      ],
    },

    {
      title: "6.3. Data Security",

      paragraphs: [
        `PERSUAIDE employs reasonable security practices and procedures consistent with applicable law, including the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 and the Digital Personal Data Protection Act, 2023 ("DPDPA"), to protect Customer Data from unauthorized access, loss, or misuse.`,

        `Users remain responsible for ensuring that their use of the platform, including any data uploaded or processed by them, complies with applicable privacy and data protection laws.`,
      ],
    },
  ],
},

{
  title: "7. Limitation of Liability",

  paragraphs: [
    `To the fullest extent permitted by applicable law, PERSUAIDE shall not be liable for any indirect, incidental, consequential, special, or punitive damages, including loss of data, loss of business opportunities, loss of goodwill, or loss of profits, arising out of or in connection with Your use of, or inability to use, the Services, even if PERSUAIDE has been advised of the possibility of such damages.`,

    `To the fullest extent permitted by applicable law, PERSUAIDE total aggregate liability arising out of or in connection with the Services or these Terms shall not exceed the total subscription fees actually paid by You to PERSUAIDE during a maximum of twelve (12) months immediately preceding the event giving rise to the claim.`,

    `Nothing in this section shall exclude or limit liability arising from fraud, wilful misconduct, breach of confidentiality, or any liability which cannot be excluded or limited under applicable law.`,
  ],
},

{
  title: "8. Privacy Policy",

  paragraphs: [
    `Your use of this Website is also governed by our Privacy Policy, which outlines how we collect, use, and protect your personal information.`,

    `You consent to all actions taken by us with respect to your information in compliance with the Privacy Policy.`,
  ],
},


{
  title: "9. User Submissions",

  paragraphs: [
    `If you submit any information to us through contact forms, demo requests, or other interactive features ("User Submissions"), you grant PERSUAIDE a non-exclusive, worldwide, royalty-free, license to use that information solely for the purpose of responding to your inquiry, providing you with our services, and improving our offerings.`,

    `You represent and warrant that you have all necessary rights, consents, and authorisations to provide your User Submissions and that the information contained therein is accurate, current, and does not violate any applicable law or the rights of any third party.`,

    `To the extent permitted by applicable law and subject to any confidentiality obligations expressly agreed in writing between you and PERSUAIDE, you acknowledge that such User Submissions may be processed by the Services for the purposes set out in these Terms and the Privacy Policy.`,
  ],
},

{
  title: "10. Third-Party Links",

  paragraphs: [
    `The Website and automated outputs may contain links to third-party websites or services that are not owned or controlled by PERSUAIDE.`,

    `We provide these links for your convenience only and do not endorse or assume any responsibility for the content, privacy policies, or practices of any third-party websites.`,

    `You access any such third-party links entirely at your own risk.`,
  ],
},

{
  title: "11. Disclaimer of Warranties",

  subsections: [
    {
      title: "11.1. Service Limitations and Availability",

      paragraphs: [
        `The Services are continuously evolving and may include features that are under development, subject to modification, or not fully optimised.`,

        `While the Services are designed to be functional and reliable, they may contain bugs, errors, or limitations, and certain functionalities may be modified, updated, or discontinued at any time at our sole discretion without prior notice, where reasonably necessary.`,

        `We do not guarantee that all features will be available at all times or that the Services will operate without interruption or error.`,

        `Any such limitations shall be subject to the limitations of liability set out in these Terms.`,

        `The Services utilise automated and probabilistic systems and may generate outputs that are inaccurate, incomplete, or not fully reliable.`,

        `You agree that you will not rely solely on the Services for any brand strategy, campaign execution, creative finalisation, or professional decision-making, and You remain responsible for independently reviewing, verifying, and assessing all outputs prior to use including but not limited to compliance with applicable advertising standards and intellectual property laws.`,
      ],
    },

    {
      title: "11.2. No Marketing Strategy or Branding Advice",

      paragraphs: [
        `The Services do not constitute branding/marketing strategy advice. All outputs are for informational assistance only and must be reviewed by a qualified professional.`,

        `PERSUAIDE is not a marketing or branding firm and does not create any client service relationship with its Users.`,

        `Use of the Services does not create any advisory, fiduciary, or professional relationship between You and PERSUAIDE.`,

        `As described above, the Services utilise automated and probabilistic systems and may generate outputs that are inaccurate, incomplete, or not tailored to Your specific branding, marketing, or commercial circumstances.`,

        `PERSUAIDE makes no representation, warranty, or guarantee, whether express or implied, that any output generated by the Platform is or will be:`,
      ],

      bullets: [
        "(a) accurate, complete, current, or error-free;",

        "(b) compliant with any applicable law, regulation, or industry standard, including but not limited to the Trade Marks Act, 1999, the Copyright Act, 1957, the Consumer Protection Act, 2019, the Information Technology Act, 2000, or the Advertising Standards Council of India (ASCI) Code;",

        "(c) free from intellectual property infringement, including trade mark, copyright, or passing-off claims;",

        "(d) suitable, appropriate, or fit for any particular purpose, campaign, audience, or medium; or",

        "(e) aligned with any applicable sector-specific guidelines, including those issued by SEBI, IRDAI, FSSAI, MCI, or any other regulatory body relevant to the user's industry.",
      ],

      extraParagraphs: [
        `The Platform's role is limited to generating outputs basis the prompts and inputs provided by the user.`,

        `The quality, accuracy, and compliance of any output is directly dependent on the quality of the inputs provided, and PERSUAIDE shall bear no responsibility for outputs generated on the basis of incomplete, inaccurate, or misleading inputs.`,

        `All users, whether marketing agencies, independent professionals, or businesses, using the Platform directly, are solely responsible for:`,
      ],
    },

    {
      title: "User Responsibilities",

      bullets: [
        "(a) reviewing, verifying, and independently assessing all outputs generated by the Services prior to any use, publication, or sharing with any third party;",

        "(b) exercising independent judgment and, where applicable, obtaining appropriate professional or legal advice before acting on or relying upon any output;",

        "(c) ensuring that all outputs comply with applicable laws and regulations, including but not limited to the Trade Marks Act, 1999, the Copyright Act, 1957, and the Consumer Protection Act, 2019;",

        "(d) ensuring compliance with applicable self-regulatory codes and guidelines, including the ASCI Code, and any sector-specific advertising standards, platform policies, or professional conduct norms relevant to the user's industry; and",

        "(e) obtaining all necessary clearances, approvals, or third-party consents including intellectual property clearances before publishing or deploying any output.",
      ],

      extraParagraphs: [
        `Users are further reminded that the ASCI Code places specific obligations on advertisers in relation to truthful representation, substantiation of claims, and responsible communication to consumers.`,

        `PERSUAIDE does not warrant that any output meets these standards, and users must independently ensure compliance before publication.`,

        `Except as expressly set out in these Terms, the Website and all automated outputs are provided on an "as is" and "as available" basis.`,

        `We do not warrant that the Website or Services will be accurate, complete, reliable, error-free, or uninterrupted, that defects will be corrected, or that the Website or the servers that make them available are free of viruses or other harmful components.`,

        `The Services shall not be construed, interpreted, or relied upon as advice, counsel, opinion, or recommendations, and You agree not to use the Services as a substitute for qualified professionals.`,

        `At our sole discretion, we may update or modify the underlying logic or data sources of the Services without notice.`,

        `PERSUAIDE does not warrant the correctness, enforceability, or suitability of any outputs for any branding or campaign purposes.`,
      ],
    },

    {
      title: "11.3. Professional Use and Risk Allocation",

      paragraphs: [
        `Where the Services are used by professionals, you acknowledge and agree that the Services are intended solely as an assistive tool and do not replace the exercise of independent professional judgment.`,

        `You remain solely responsible for all professional decisions, advice, creatives, presentations, made to clients or the larger audiences of your brand.`,

        `Without limiting the foregoing, You agree that:`,
      ],

      bullets: [
        "You will independently review, verify, and validate all outputs generated by the Services prior to any use or reliance;",

        "You will ensure that all outputs are accurate, complete, and compliant with applicable laws, do not lead to any IP infringement, and are in accordance with applicable industry standards; and",

        "You will exercise your own professional skill, care, and diligence in all matters in which the Services are used.",
      ],

      extraParagraphs: [
        `To the fullest extent permitted by applicable law, PERSUAIDE shall not be responsible or liable to the extent that any claims, losses, or liabilities arise from, relate to, or are attributable to the use of the Services or the automated outputs generated therefrom in a professional capacity, including any reliance placed on outputs without appropriate independent review, validation and professional judgment.`,

        `Nothing in this section shall be construed to limit or exclude any liability which cannot be excluded under applicable law.`,
      ],
    },
  ],
},
{
  title: "12. Termination",

  subsections: [
    {
      title: "12.1. Termination by User",

      paragraphs: [
        `Customers may cancel their subscription at any time by sending an email to anand@persuaide.ai.`,

        `Upon termination, access to the platform and any stored Customer Data will be subject to the Data Retention policies set out in these Terms.`,
      ],
    },

    {
      title: "12.2. Termination by PERSUAIDE",

      paragraphs: [
        `PERSUAIDE reserves the right to terminate access at its sole discretion for:`,
      ],

      bullets: [
        "Breach of these Terms.",

        "Non-payment of fees.",

        "Engagement in prohibited actions.",
      ],
    },

    {
      title: "12.3. Effect of Termination",

      paragraphs: [
        `Upon termination, access to the platform will be revoked, and the User must settle any outstanding payments.`,

        `Any Customer Data will be handled in accordance with the Privacy Policy, including applicable data retention and deletion practices.`,

        `Certain provisions of these Terms, including but not limited to intellectual property, limitation of liability, indemnity, and dispute resolution, shall survive termination.`,
      ],
    },
  ],
},
{
  title: "13. Indemnification",

  paragraphs: [
    `You agree to defend, indemnify, and hold harmless PERSUAIDE and their affiliates, officers, directors, employees, and agents from and against any third party claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising from or related to:`,

  ],

  bullets: [
    "(i) Your use of the Website;",

    "(ii) Your violation of these Terms;",

    "(iii) Your User Submissions; or",

    "(iv) Your violation of any law or the rights of any third party.",
  ],
},
{
  title: "14. Modifications to the Terms",

  paragraphs: [
    `We reserve the right to modify or replace these Terms at any time in our sole and absolute discretion.`,

    `We will post the updated Terms on this page and indicate the "Last Updated" date at the top.`,

    `We will provide reasonable notice of any material changes to these Terms, where feasible.`,

    `Your continued use of the Website after any such changes constitutes Your acceptance of the new Terms.`,
  ],
},
{
  title: "15. Governing Law and Jurisdiction",

  paragraphs: [
    `These Terms of Use are governed by and construed in accordance with the laws of India.`,

    `Any disputes arising from or related to Your use of the Website shall be subject to the exclusive jurisdiction of the courts in Mumbai, Maharashtra, India.`,

    `Parties will attempt amicable resolution before seeking legal recourse.`,
  ],
},
{
  title: "16. General Provisions",

  bullets: [
    `Force Majeure: PERSUAIDE shall not be liable for any failure or delay in the performance of its obligations under these Terms if such failure or delay is caused by events beyond its reasonable control, including but not limited to acts of God, flood, fire, earthquake, war, terrorism, riot, civil unrest, pandemic, epidemic, national emergency, strikes, labor disputes, telecommunication or internet outages, power failures, or acts of government authorities.`,

    `Severability: If any provision of these Terms is held by a court to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.`,

    `Waiver: No waiver by PERSUAIDE of any term or condition set forth in these Terms shall be deemed a further or continuing waiver of such term or condition.`,

    `Entire Agreement: These Terms and our Privacy Policy constitute the entire agreement between You and PERSUAIDE regarding Your use of the Website and supersede all prior and contemporaneous understandings.`,
  ],
},

{
  title: "17. Grievance Officer",

  paragraphs: [
    `In accordance with India's Information Technology Act, 2000, and the rules thereunder, the designated Grievance Officer is:`,

    `Upon receipt of a complaint, the Grievance Officer shall acknowledge the same within forty-eight (48) hours and endeavour to resolve the complaint within fifteen (15) calendar days of its receipt.`,

    `Please contact the Grievance Officer for any complaints or concerns about these Terms of Use.`,
  ],

  contact: {
    name: "Anand Damani",
    designation: "Grievance Officer",
    email: "anand@persuaide.ai",
  },
},
{
  title: "18. Contact Us",

  paragraphs: [
    `If You have any questions or concerns about these Terms of Use, please contact us at:`,
  ],

  contact: {
    name: "Persuaide Software Solutions Pvt. Ltd.",
    designation:
      "501 Glamourglen, Ambedkar road, Bandra W, Mumbai - 400050, Maharashtra, India.",
    email: "anand@persuaide.ai",
  },
}

  ],
};

type Section = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
  extraParagraphs?: string[];
  subsections?: {
    title: string;
    paragraphs?: string[];
    bullets?: string[];
    extraParagraphs?: string[];
  }[];
  contact?: {
    name?: string;
    designation?: string;
    email?: string;
  };
};

export default function TermsPage() {
  return (
    <main className="flex-1 flex flex-col bg-white font-sans">
      {/* Hero Header */}
      <section className="relative pt-40 pb-24 px-6 md:px-8 bg-[#0038FF] overflow-hidden flex flex-col items-center justify-center text-center select-none">
        
        {/* Background Gradient */}
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_30%,#0038FF_0%,#002DB3_50%,#001980_100%)] pointer-events-none z-0" />

        {/* Grid Overlay */}
        <div className="absolute inset-0 bg-grid-pattern opacity-25 pointer-events-none z-10" />

        {/* Navbar */}
        <Navbar />

        {/* Hero Content */}
        <div className="relative z-20 max-w-7xl mx-auto mt-8 flex flex-col items-center justify-center text-center">
          <div className="max-w-3xl text-center">
            <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-white mb-4 leading-[1.1]">
              Terms of Service
            </h1>

            <p className="text-blue-100/70 text-[12px] md:text-sm font-semibold uppercase tracking-widest">
              Last Updated: 26 May 2026
            </p>
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 md:py-24 px-6 md:px-8 w-full flex-1">
        <div className="max-w-7xl mx-auto relative">
          <article className="max-w-3xl mx-auto w-full text-left text-slate-600 text-base md:text-lg leading-relaxed space-y-10">

            {/* Intro */}
            {termsOfServiceData.intro.map((paragraph, index) => (
              <p key={index}>{paragraph}</p>
            ))}

            <hr className="border-slate-100 w-full" />

            {/* Dynamic Sections */}
            {termsOfServiceData.sections.map(
              (section: Section, index: number) => (
                <div key={index} className="space-y-4 w-full">

                  {/* Title */}
                  <h2 className="text-2xl md:text-3xl font-bold text-slate-900 tracking-tight">
                    {section.title}
                  </h2>

                  {/* Paragraphs */}
                  {section?.paragraphs?.map(
                    (paragraph, paragraphIndex) => (
                      <p
                        key={paragraphIndex}
                        className="whitespace-pre-line"
                      >
                        {paragraph}
                      </p>
                    )
                  )}

                  {/* Bullets */}
                  {section?.bullets && (
                    <ul className="list-disc pl-5 space-y-2 mt-2 text-slate-600 marker:text-[#0038FF]">
                      {section.bullets.map(
                        (bullet, bulletIndex) => (
                          <li key={bulletIndex}>
                            {bullet}
                          </li>
                        )
                      )}
                    </ul>
                  )}

                  {/* Extra Paragraphs */}
                  {section?.extraParagraphs?.map(
                    (paragraph, extraIndex) => (
                      <p
                        key={extraIndex}
                        className="whitespace-pre-line"
                      >
                        {paragraph}
                      </p>
                    )
                  )}

                  {/* Subsections */}
                  {section?.subsections && (
                    <div className="space-y-6 mt-6">
                      {section.subsections.map(
                        (subsection, subIndex) => (
                          <div
                            key={subIndex}
                            className="space-y-3"
                          >
                            <h3 className="text-xl md:text-2xl font-semibold text-slate-900 tracking-tight">
                              {subsection.title}
                            </h3>

                            {/* Subsection Paragraphs */}
                            {subsection?.paragraphs?.map(
                              (paragraph, pIndex) => (
                                <p
                                  key={pIndex}
                                  className="whitespace-pre-line"
                                >
                                  {paragraph}
                                </p>
                              )
                            )}

                            {/* Subsection Bullets */}
                            {subsection?.bullets && (
                              <ul className="list-disc pl-5 space-y-2 mt-2 text-slate-600 marker:text-[#0038FF]">
                                {subsection.bullets.map(
                                  (
                                    bullet,
                                    bulletIndex
                                  ) => (
                                    <li key={bulletIndex}>
                                      {bullet}
                                    </li>
                                  )
                                )}
                              </ul>
                            )}

                            {/* Subsection Extra Paragraphs */}
                            {subsection?.extraParagraphs?.map(
                              (
                                paragraph,
                                extraIndex
                              ) => (
                                <p
                                  key={extraIndex}
                                  className="whitespace-pre-line"
                                >
                                  {paragraph}
                                </p>
                              )
                            )}
                          </div>
                        )
                      )}
                    </div>
                  )}

                  {/* Contact */}
                  {section?.contact && (
                    <div className="space-y-2 pt-2">
                      {section.contact.name && (
                        <p>
                          <span className="font-semibold text-slate-900">
                            Name:
                          </span>{" "}
                          {section.contact.name}
                        </p>
                      )}

                      {section.contact.designation && (
                        <p>
                          <span className="font-semibold text-slate-900">
                            Designation:
                          </span>{" "}
                          {section.contact.designation}
                        </p>
                      )}

                      {section.contact.email && (
                        <p>
                          <span className="font-semibold text-slate-900">
                            Email:
                          </span>{" "}
                          <a
                            href={`mailto:${section.contact.email}`}
                            className="text-[#0038FF] hover:underline"
                          >
                            {section.contact.email}
                          </a>
                        </p>
                      )}
                    </div>
                  )}
                </div>
              )
            )}
          </article>
        </div>
      </section>

      <Footer />
    </main>
  );
}